from django.urls import path

from . import views


app_name = "fmea"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("fmea/projects/", views.project_list, name="project_list"),
    path("fmea/projects/<str:stable_id>/", views.project_detail, name="project_detail"),
    path("fmea/projects/<str:stable_id>/team/", views.project_team, name="project_team"),
    path("context/", views.engineering_context, name="engineering_context"),
    path("systems/", views.system_list, name="system_list"),
    path("systems/new/", views.system_create, name="system_create"),
    path("systems/<str:stable_id>/", views.system_detail, name="system_detail"),
    path("systems/<str:stable_id>/edit/", views.system_edit, name="system_edit"),
    path("dfmea/", views.dfmea_worksheet, name="dfmea_worksheet"),
    path("pfmea/", views.pfmea_worksheet, name="pfmea_worksheet"),
    path("projects/create/", views.create_project, name="create_project"),
    path("fmeas/create/", views.create_fmea, name="create_fmea"),
    path("fmea/<str:stable_id>/", views.fmea_detail, name="fmea_detail"),
    path("fmea/<str:stable_id>/failure-modes/add/", views.add_failure_mode, name="add_failure_mode"),
    path("fmea/<str:stable_id>/functions/add/", views.add_function, name="add_function"),
    path(
        "process-characteristics/",
        views.process_characteristic_list,
        name="process_characteristic_list",
    ),
    path(
        "process-characteristics/new/",
        views.new_process_characteristic,
        name="new_process_characteristic",
    ),
    path(
        "process-characteristics/<str:stable_id>/",
        views.process_characteristic_detail,
        name="process_characteristic_detail",
    ),
    path(
        "processes/<str:stable_id>/flow/",
        views.process_flow,
        name="process_flow",
    ),
    path("risk-matrix/", views.risk_matrix, name="risk_matrix"),
    path("risk-matrix/cell/", views.risk_matrix_cell, name="risk_matrix_cell"),
    path("risk-matrix/top/", views.risk_matrix_top, name="risk_matrix_top"),
    path("risk-trajectory/", views.risk_trajectory_index, name="risk_trajectory_index"),
    path(
        "failure-mode/<str:stable_id>/risk-trajectory/",
        views.risk_trajectory,
        name="risk_trajectory",
    ),
    path("cause-influences/", views.cause_influence_list, name="cause_influence_list"),
    path("cause-influences/new/", views.new_cause_influence, name="new_cause_influence"),
    path("cause-influences/create/", views.create_cause_influence_view, name="create_cause_influence"),
    path("cause-influences/<str:stable_id>/", views.cause_influence_detail, name="cause_influence_detail"),
    path(
        "cause-influences/<str:stable_id>/transition/",
        views.transition_cause_influence_view,
        name="transition_cause_influence",
    ),
    path(
        "failure-modes/<str:stable_id>/ishikawa-board/",
        views.ishikawa_board,
        name="ishikawa_board",
    ),
    path("failure-mode/<str:stable_id>/effects/add/", views.add_failure_effect, name="add_failure_effect"),
    path("failure-mode/<str:stable_id>/causes/add/", views.add_failure_cause, name="add_failure_cause"),
    path("failure-mode/<str:stable_id>/evaluate/", views.evaluate_failure, name="evaluate_failure"),
    path("cause/<str:stable_id>/prevention-controls/add/", views.add_prevention_control, name="add_prevention_control"),
    path("cause/<str:stable_id>/detection-controls/add/", views.add_detection_control, name="add_detection_control"),
    path("cause/<str:stable_id>/actions/add/", views.add_action_to_cause, name="add_action_to_cause"),
    path(
        "failure-mode/<str:stable_id>/actions/add/",
        views.add_action_to_failure_mode,
        name="add_action_to_failure_mode",
    ),
    path("actions/<str:stable_id>/", views.action_detail, name="action_detail"),
    path("failure-modes/", views.failure_mode_list, name="failure_mode_list"),
    path("causes/", views.failure_cause_list, name="failure_cause_list"),
    path("effects/", views.failure_effect_list, name="failure_effect_list"),
    path("prevention-controls/", views.prevention_control_list, name="prevention_control_list"),
    path("detection-controls/", views.detection_control_list, name="detection_control_list"),
    path("actions/", views.action_list, name="action_list"),
    path("validation-tests/", views.validation_test_list, name="validation_test_list"),
    path("validation-tests/new/", views.new_validation_test, name="new_validation_test"),
    path("validation-tests/<str:stable_id>/", views.validation_test_detail, name="validation_test_detail"),
    path("changes/", views.change_list, name="change_list"),
    path("changes/new/", views.new_change, name="new_change"),
    path("changes/<str:stable_id>/edit/", views.edit_change, name="edit_change"),
    path("changes/<str:stable_id>/", views.change_detail, name="change_detail"),
    path("characteristic-links/", views.characteristic_link_list, name="characteristic_link_list"),
    path(
        "characteristic-links/create/",
        views.characteristic_link_create,
        name="characteristic_link_create",
    ),
    path(
        "characteristic-links/<str:stable_id>/delete/",
        views.characteristic_link_delete,
        name="characteristic_link_delete",
    ),
]
