# Generated by Open-FMEA on 2026-08-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fmea_domain.identifiers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stable_id",
                    models.CharField(
                        db_index=True,
                        default=fmea_domain.identifiers.new_stable_id,
                        editable=False,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("document_version", models.CharField(db_index=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("reviewing", "Reviewing"), ("completed", "Completed")],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmea_import_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportCandidateRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stable_id", models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ("schema_version", models.CharField(default="1.0", max_length=16)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("extracted_value", models.TextField()),
                ("suggested_domain_type", models.CharField(max_length=64)),
                ("source_document_id", models.CharField(max_length=128)),
                ("document_version", models.CharField(max_length=64)),
                ("workbook_name", models.CharField(max_length=255)),
                ("sheet_name", models.CharField(max_length=255)),
                ("row_number", models.PositiveIntegerField()),
                ("column_name", models.CharField(max_length=255)),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[("deterministic", "Deterministic"), ("ai", "AI")],
                        max_length=32,
                    ),
                ),
                ("parser_version", models.CharField(max_length=32)),
                ("parsing_confidence", models.FloatField(blank=True, null=True)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("validation_issues", models.JSONField(blank=True, default=list)),
                ("relationship_suggestions", models.JSONField(blank=True, default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("accepted", "Accepted"),
                            ("modified", "Modified"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                            ("needs_clarification", "Needs Clarification"),
                        ],
                        default="unreviewed",
                        max_length=32,
                    ),
                ),
                ("accepted_object_stable_id", models.CharField(blank=True, max_length=128, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmea_import_candidate_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="fmea_review.importsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "row_number", "column_name"],
            },
        ),
        migrations.AddIndex(
            model_name="importcandidaterecord",
            index=models.Index(fields=["session", "review_status"], name="fmea_review_session_bcb716_idx"),
        ),
        migrations.AddIndex(
            model_name="importcandidaterecord",
            index=models.Index(fields=["suggested_domain_type"], name="fmea_review_suggest_e2b2ec_idx"),
        ),
    ]
