# Generated by Django 5.2.17 on 2026-08-31 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FmeaRowGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('sheet_name', models.CharField(max_length=255)),
                ('row_start', models.PositiveIntegerField()),
                ('row_end', models.PositiveIntegerField()),
                ('source_range', models.CharField(max_length=255)),
                ('parser_version', models.CharField(max_length=32)),
                ('detected_fields', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accepted', 'Accepted'), ('modified', 'Modified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('needs_clarification', 'Needs Clarification')], default='unreviewed', max_length=32)),
                ('accepted_object_stable_ids', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmea_row_group_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_groups', to='fmea_review.importsession')),
            ],
            options={
                'ordering': ['session', 'sheet_name', 'row_start', 'row_end'],
            },
        ),
        migrations.AddField(
            model_name='importcandidaterecord',
            name='row_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='fmea_review.fmearowgroup'),
        ),
        migrations.AddIndex(
            model_name='fmearowgroup',
            index=models.Index(fields=['session', 'review_status'], name='fmea_row_group_session_idx'),
        ),
        migrations.AddIndex(
            model_name='fmearowgroup',
            index=models.Index(fields=['sheet_name', 'row_start'], name='fmea_row_group_source_idx'),
        ),
    ]
