# Generated by Django 4.1.5 on 2026-08-30 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fmea_domain.identifiers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_special', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomainRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_stable_id', models.CharField(db_index=True, max_length=128)),
                ('target_stable_id', models.CharField(db_index=True, max_length=128)),
                ('relationship_type', models.CharField(max_length=128)),
                ('provenance', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rating_scales', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FMEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fmea_type', models.CharField(choices=[('design', 'Design'), ('process', 'Process'), ('product', 'Product'), ('software', 'Software'), ('system', 'System')], default='process', max_length=32)),
                ('scope', models.TextField(blank=True)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('obsolete', 'Obsolete')], default='draft', max_length=32)),
                ('team', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FMEAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=64)),
                ('severity', models.PositiveSmallIntegerField()),
                ('occurrence', models.PositiveSmallIntegerField()),
                ('detection', models.PositiveSmallIntegerField()),
                ('result', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('trigger', models.CharField(default='manual', max_length=64)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_evaluations', to='fmea_app.evaluationdefinition')),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_evaluations', to='fmea_app.failuremode')),
            ],
            options={
                'ordering': ['-evaluated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='fmea_app.function')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('failure_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_actions', to='fmea_app.failurecause')),
                ('failure_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_actions', to='fmea_app.failuremode')),
                ('responsible_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_actions', to='fmea_app.responsiblerole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('part_number', models.CharField(blank=True, max_length=128)),
                ('fmea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fmea_app.fmea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('process_code', models.CharField(blank=True, max_length=128)),
                ('fmea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='fmea_app.fmea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreventionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('failure_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevention_controls', to='fmea_app.failurecause')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.CharField(blank=True, max_length=64)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='fmea_app.process')),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('detection_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_methods', to='fmea_app.detectioncontrol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='function',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='fmea_app.operation'),
        ),
        migrations.AddField(
            model_name='function',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='fmea_app.product'),
        ),
        migrations.CreateModel(
            name='FMEARevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('lifecycle_from', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('obsolete', 'Obsolete')], max_length=32)),
                ('lifecycle_to', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('obsolete', 'Obsolete')], max_length=32)),
                ('reason', models.TextField()),
                ('actor', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fmea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='fmea_app.fmea')),
            ],
            options={
                'ordering': ['revision_number'],
            },
        ),
        migrations.AddField(
            model_name='fmea',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmeas', to='fmea_app.fmeaproject'),
        ),
        migrations.AddField(
            model_name='failuremode',
            name='fmea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_modes', to='fmea_app.fmea'),
        ),
        migrations.AddField(
            model_name='failuremode',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_modes', to='fmea_app.function'),
        ),
        migrations.AddField(
            model_name='failuremode',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_modes', to='fmea_app.requirement'),
        ),
        migrations.CreateModel(
            name='FailureMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('failure_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanisms', to='fmea_app.failurecause')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='fmea_app.failuremode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='failurecause',
            name='failure_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='fmea_app.failuremode'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference_uri', models.CharField(blank=True, max_length=500)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='fmea_app.recommendedaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectivenessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_verifications', to='fmea_app.recommendedaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='domainrelationship',
            index=models.Index(fields=['source_stable_id', 'relationship_type'], name='fmea_app_do_source__ece6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='domainrelationship',
            index=models.Index(fields=['target_stable_id', 'relationship_type'], name='fmea_app_do_target__2bc119_idx'),
        ),
        migrations.AddField(
            model_name='detectioncontrol',
            name='failure_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_controls', to='fmea_app.failurecause'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='fmea_app.requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='fmearevision',
            unique_together={('fmea', 'revision_number')},
        ),
    ]
