# Generated by Django 5.2.17 on 2026-09-01 17:36

import django.db.models.deletion
import fmea_domain.identifiers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseCategoryScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CauseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['scheme_id', 'sort_order', 'name'],
                'unique_together': {('scheme_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CauseInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_type', models.CharField(choices=[('FailureCause', 'Failure Cause'), ('FailureMechanism', 'Failure Mechanism')], max_length=64)),
                ('target_id', models.CharField(db_index=True, max_length=128)),
                ('target_type', models.CharField(choices=[('FailureMode', 'Failure Mode'), ('FailureCause', 'Failure Cause')], max_length=64)),
                ('influence_type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('suspected', 'Suspected'), ('possible', 'Possible'), ('correlated', 'Correlated'), ('experimentally_supported', 'Experimentally Supported'), ('confirmed_root_cause', 'Confirmed Root Cause'), ('rejected', 'Rejected')], db_index=True, default='suspected', max_length=64)),
                ('cause_category_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('strength', models.CharField(blank=True, max_length=128, null=True)),
                ('evidence_ids', models.JSONField(blank=True, default=list)),
                ('source_context', models.CharField(default='FMEA', max_length=128)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_influence_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_type', 'target_id', 'status', 'source_type', 'source_id'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='cause_infl_target_idx'), models.Index(fields=['source_type', 'source_id'], name='cause_infl_source_idx'), models.Index(fields=['status', 'cause_category_id'], name='cause_infl_status_cat_idx')],
            },
        ),
    ]
