# Generated by Django 5.2.17 on 2026-09-03 19:31

import django.db.models.deletion
import fmea_domain.identifiers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0004_processcharacteristic_and_widen_causeinfluence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fmeaproject',
            name='project_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fmeaproject',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('fmea_leader', 'FMEA Leader'), ('pm_fmea_responsible', 'PM-FMEA Responsible'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fmea_app.fmeaproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__name', 'role', 'user__email', 'user__last_name', 'user__first_name'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
