# Generated by Django 5.2.17 on 2026-09-05 07:14

import django.db.models.deletion
import fmea_domain.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0006_system_process_system_product_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='primary_classification_id',
        ),
        migrations.CreateModel(
            name='ClassificationTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='fmea_app.classificationscheme')),
            ],
            options={
                'ordering': ['scheme_id', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productcharacteristic',
            name='primary_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_characteristics', to='fmea_app.classificationterm'),
        ),
    ]
