# Generated by Django 5.2.17 on 2026-09-05 07:21

import django.db.models.deletion
import fmea_domain.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0007_classificationscheme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('test_type', models.CharField(choices=[('validation', 'Validation'), ('verification', 'Verification'), ('reliability', 'Reliability'), ('acceptance', 'Acceptance')], max_length=32)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('objective', models.TextField(blank=True)),
                ('nominal_target', models.CharField(blank=True, max_length=255)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('result_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=32)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('executed_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=32)),
                ('lifecycle_gate', models.CharField(choices=[('concept_design', 'Concept/Design'), ('design_verification', 'Design Verification'), ('process_validation', 'Process Validation'), ('pre_production', 'Pre-Production'), ('serial_production', 'Serial Production'), ('current', 'Current')], max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_execution', 'In Execution'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planned', max_length=32)),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_tests', to='fmea_app.failuremode')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_tests', to='fmea_app.responsiblerole')),
                ('recommended_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_tests', to='fmea_app.recommendedaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
