# Generated by Django 5.2.17 on 2026-09-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0008_validationtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='open', max_length=32),
        ),
    ]
