# Generated by Django 5.2.17 on 2026-09-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0009_alter_recommendedaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcharacteristic',
            name='control_type',
            field=models.CharField(blank=True, choices=[('administrative', 'Administrative'), ('measurement', 'Measurement'), ('detection', 'Detection'), ('monitoring', 'Monitoring'), ('poka_yoke', 'Poka-Yoke'), ('test', 'Test')], max_length=32),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='effectiveness',
            field=models.CharField(choices=[('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('not_effective', 'Not Effective'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='frequency_trigger',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_process_characteristics', to='fmea_app.responsiblerole'),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='reaction_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='resource_equipment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='review_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processcharacteristic',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
    ]
