# Generated by Django 5.2.17 on 2026-09-05 13:18

import django.db.models.deletion
import fmea_domain.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0010_process_characteristic_control_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('design', 'Design'), ('supplier', 'Supplier'), ('regulatory', 'Regulatory'), ('process', 'Process'), ('material', 'Material')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('impact_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('status', models.CharField(choices=[('under_analysis', 'Under Analysis'), ('in_progress', 'In Progress'), ('open', 'Open'), ('closed', 'Closed')], default='under_analysis', max_length=32)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('affected_failure_modes', models.ManyToManyField(blank=True, related_name='affecting_changes', to='fmea_app.failuremode')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='fmea_app.responsiblerole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
