# Generated by Django 5.2.17 on 2026-09-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0011_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskevaluation',
            name='lifecycle_gate',
            field=models.CharField(choices=[('concept_design', 'Concept/Design'), ('design_verification', 'Design Verification'), ('process_validation', 'Process Validation'), ('pre_production', 'Pre-Production (PPAP)'), ('serial_production', 'Serial Production (SOP)'), ('current', 'Current')], default='current', max_length=32),
        ),
    ]
