# Generated by Django 5.2.17 on 2026-09-05 13:39

import django.db.models.deletion
import fmea_domain.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmea_app', '0012_riskevaluation_lifecycle_gate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(db_index=True, default=fmea_domain.identifiers.new_stable_id, editable=False, max_length=128, unique=True)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('drives', 'Drives'), ('influences', 'Influences'), ('affected_by', 'Affected By'), ('constrained_by', 'Constrained By'), ('supports', 'Supports'), ('required_by', 'Required By')], max_length=32)),
                ('strength', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], max_length=16)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('from_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='fmea_app.productcharacteristic')),
                ('to_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='fmea_app.productcharacteristic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
